### ISSUE TITLE
Tooltips Get Stuck

### ISSUE THREAD

**Issue by m-macdonald** [TheAngriestDog/JS-Gantt-Chart#3]
Tooltips seem to be getting stuck on occasion. Haven't figured out why yet.

**Comment by dawsonx** [comment]
# Tooltips here! Get your tooltips!
#4

**Comment by dawsonx** [comment]
#2 i see an issue here

**Comment by dawsonx** [comment]
#1 possibly another issue here

**Comment by dawsonx** [comment]
not certain

**Comment by TheAngriestDog** [comment]
What would I do without you?

**Comment by dawsonx** [comment]
probably die idk

**Comment by dawsonx** [comment]
# HAHA BAD

**Comment by dawsonx** [comment]
so i saw a goat today

**Comment by dawsonx** [comment]
3 even

**Comment by dawsonx** [comment]
4*
